apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 1h
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: kibana
  interval: 1h0m0s
  chart:
    spec:
      version: "7.17.3"
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: kibana
        namespace: logging
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"
    lifecycle:
      postStart:
        exec:
          command:
            - bash
            - -c
            - |
              #!/bin/bash
              # Import a dashboard
              while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L http://localhost:5601)" != "200" ]]; do sleep 1; done
              curl -X POST "http://localhost:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d'{"index_pattern":{"title":"logstash-*","timeFieldName":"@timestamp"}}'
