apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kafka
  namespace: logging
spec:
  interval: 1h
  type: oci                                 # ← this is the key change
  url: oci://registry-1.docker.io/bitnamicharts  # ← base OCI repo (no /kafka here)

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka
  namespace: logging
spec:
  interval: 1h
  chart:
    spec:
      chart: kafka
      version: 32.4.3           # or pin exact version e.g. 32.4.3 → check latest!
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: logging

  values:

    kraft:
      enabled: true
      clusterId: "keep-the-same-value-after-first-install"   # very important!
      version: 1                           # ← force dynamic quorum (bootstrap.servers, no static voters needed)

    image:
      registry: docker.io
      repository: bitnamilegacy/kafka           # ← changed from bitnamilegacy
      tag: "3.8.0-debian-12-r3"          # check https://hub.docker.com/r/bitnami/kafka/tags

    controller:
      replicaCount: 3                     # strongly recommended
      quorumBootstrapServers: ""     # leave empty → chart auto-fills with all controller pods
      persistence:
        enabled: true
        size: 50Gi
      heapOpts: "-Xmx4g -Xms4g"           # example – tune per node size

    broker:
      replicaCount: 0                     # you can keep 0 if you want combined nodes

    # If you want separate controller + broker nodes (common pattern):
    # controller:
    #   replicaCount: 3
    #   controllerOnly: true
    # broker:
    #   replicaCount: 3..6

    listeners:
      client:
        protocol: SASL_PLAINTEXT
      interbroker:
        protocol: SASL_PLAINTEXT
      controller:
        protocol: SASL_PLAINTEXT

    sasl:
      enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      interBrokerMechanism: SCRAM-SHA-256     # more secure than PLAIN
      controllerMechanism:  SCRAM-SHA-256

      interbroker:
        user:     "internal"
        password: "change-me-please-very-long-random"

      controller:
        user:     "controller"
        password: "also-very-long-random-secret"

      client:
        users:
          - "app1"
          - "logstash"
          - "metrics"
        passwords:
          - "long-secret-app1-2026"
          - "long-secret-logstash"
          - "long-secret-metrics"

    # Very useful in production / debugging
    log4j: |
      log4j.rootLogger=INFO, stdout
      log4j.appender.stdout=org.apache.log4j.ConsoleAppender
      log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
      log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

    provisioning:
      enabled: true
      topics:
        - name: logstash
          partitions: 8
          replicationFactor: 3          # match number of data nodes
          config:
            retention.ms: 604800000     # 7 days
            min.insync.replicas: 2

    resources:
      requests:
        cpu: 1500m
        memory: 5Gi
      limits:
        cpu: 3500m
        memory: 8Gi

    persistence:
      size: 100Gi                         # real production value example

    # Optional – very useful
    metrics:
      kafka:
        enabled: false
      jmx:
        enabled: false
      serviceMonitor:
        enabled: false
