---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      version: "1.19.0"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      version: "1.19.0"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h
  install:
    remediation:
      retries: 10
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: false
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 512Mi
