apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
labels:
  - pairs:
      managed_by: caveman
      environment: lab
    includeSelectors: false
resources:
  - namespace.yaml
  - grafana.yaml
  - prometheus.yaml
  - random-logger-dashboard.yaml
