apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: top-speed-windowing-0
spec:
  deploymentName: flink-stream-deployment
  job:
    jarURI: https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.16.1/flink-examples-streaming_2.12-1.16.1-TopSpeedWindowing.jar
    parallelism: 2
    upgradeMode: stateless
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: top-speed-windowing-1
spec:
  deploymentName: flink-stream-deployment
  job:
    jarURI: https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.16.1/flink-examples-streaming_2.12-1.16.1-TopSpeedWindowing.jar
    parallelism: 6
    upgradeMode: stateless
